//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace datos_red_alert
{
    using System;
    using System.Collections.Generic;
    
    public partial class Apl_Parametros_Correo
    {
        public int Parametro_ID { get; set; }
        public string Email { get; set; }
        public string Contrasena { get; set; }
        public Nullable<int> Puerto { get; set; }
        public string Host { get; set; }
    }
}
