//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace datos_red_alert
{
    using System;
    using System.Collections.Generic;
    
    public partial class Apl_Usuarios
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Apl_Usuarios()
        {
            this.Apl_Rel_Usuarios_Roles = new HashSet<Apl_Rel_Usuarios_Roles>();
        }
    
        public int Empresa_ID { get; set; }
        public int Usuario_ID { get; set; }
        public int Estatus_ID { get; set; }
        public int Tipo_Usuario_ID { get; set; }
        public string Usuario { get; set; }
        public string Password { get; set; }
        public Nullable<System.DateTime> Fecha_Expira_Contrasenia { get; set; }
        public string Email { get; set; }
        public string No_Intentos_Recuperar { get; set; }
        public string Token_Confirmacion { get; set; }
        public System.DateTime Fecha_Token { get; set; }
        public string Respuesta_Secreta { get; set; }
        public string Usuario_Creo { get; set; }
        public Nullable<System.DateTime> Fecha_Creo { get; set; }
        public string Usuario_Modifico { get; set; }
        public Nullable<System.DateTime> Fecha_Modifico { get; set; }
        public Nullable<System.DateTime> Fecha_Ultimo_Acceso { get; set; }
        public Nullable<System.DateTime> Fecha_Intento_Acceso { get; set; }
        public string Usuario_login { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Apl_Rel_Usuarios_Roles> Apl_Rel_Usuarios_Roles { get; set; }
        public virtual Apl_Tipos_Usuarios Apl_Tipos_Usuarios { get; set; }
    }
}
