//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace datos_red_alert
{
    using System;
    using System.Collections.Generic;
    
    public partial class Apl_Estatus
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Apl_Estatus()
        {
            this.Cat_Consejos_Medicos = new HashSet<Cat_Consejos_Medicos>();
            this.Cat_Especialidades = new HashSet<Cat_Especialidades>();
            this.Cat_Medicos = new HashSet<Cat_Medicos>();
            this.Cat_Mes_Aplicacion_Vacuna = new HashSet<Cat_Mes_Aplicacion_Vacuna>();
            this.Cat_Registro_Civil = new HashSet<Cat_Registro_Civil>();
            this.Cat_Tipo_Instalacion = new HashSet<Cat_Tipo_Instalacion>();
            this.Cat_Ubicaciones = new HashSet<Cat_Ubicaciones>();
            this.Cat_Vacunas = new HashSet<Cat_Vacunas>();
            this.Cat_Tramites = new HashSet<Cat_Tramites>();
        }
    
        public int Estatus_ID { get; set; }
        public string Estatus { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cat_Consejos_Medicos> Cat_Consejos_Medicos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cat_Especialidades> Cat_Especialidades { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cat_Medicos> Cat_Medicos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cat_Mes_Aplicacion_Vacuna> Cat_Mes_Aplicacion_Vacuna { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cat_Registro_Civil> Cat_Registro_Civil { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cat_Tipo_Instalacion> Cat_Tipo_Instalacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cat_Ubicaciones> Cat_Ubicaciones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cat_Vacunas> Cat_Vacunas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cat_Tramites> Cat_Tramites { get; set; }
    }
}
