//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace datos_red_alert
{
    using System;
    using System.Collections.Generic;
    
    public partial class Apl_Opiniones
    {
        public int Opinion_Id { get; set; }
        public Nullable<decimal> Calificacion { get; set; }
        public string Comentarios { get; set; }
        public Nullable<int> UsuarioMoviId { get; set; }
        public Nullable<int> Medico_Id { get; set; }
    
        public virtual Cat_Medicos Cat_Medicos { get; set; }
        public virtual Apl_Usuarios_Movil Apl_Usuarios_Movil { get; set; }
    }
}
