//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace datos_red_alert
{
    using System;
    using System.Collections.Generic;
    
    public partial class Apl_Historial_Bebes
    {
        public int HistorialId { get; set; }
        public int BebeId { get; set; }
        public string Tipo { get; set; }
        public Nullable<int> MesesVacuna { get; set; }
        public string Descripcion { get; set; }
        public Nullable<System.DateTime> FechaCreo { get; set; }
        public Nullable<decimal> Peso { get; set; }
        public Nullable<decimal> Estatura { get; set; }
        public Nullable<int> RecordatorioDetalleId { get; set; }
        public Nullable<int> RecordatorioId { get; set; }
    
        public virtual Apl_Bebes Apl_Bebes { get; set; }
        public virtual Ope_Recordatorios_Detalles Ope_Recordatorios_Detalles { get; set; }
        public virtual Ope_Recordatorios Ope_Recordatorios { get; set; }
    }
}
