//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace datos_red_alert
{
    using System;
    using System.Collections.Generic;
    
    public partial class Apl_Bebes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Apl_Bebes()
        {
            this.Apl_Historial_Bebes = new HashSet<Apl_Historial_Bebes>();
            this.Ope_Recordatorios = new HashSet<Ope_Recordatorios>();
            this.Ope_Aplicacion_Vacunas = new HashSet<Ope_Aplicacion_Vacunas>();
        }
    
        public int BebeId { get; set; }
        public string Nombre { get; set; }
        public string Apellidos { get; set; }
        public Nullable<System.DateTime> FechaNacimiento { get; set; }
        public Nullable<bool> Sexo { get; set; }
        public string Padecimientos { get; set; }
        public Nullable<int> UsuarioId { get; set; }
        public string RutaImagen { get; set; }
    
        public virtual Apl_Usuarios_Movil Apl_Usuarios_Movil { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Apl_Historial_Bebes> Apl_Historial_Bebes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ope_Recordatorios> Ope_Recordatorios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ope_Aplicacion_Vacunas> Ope_Aplicacion_Vacunas { get; set; }
    }
}
