//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace datos_red_alert
{
    using System;
    using System.Collections.Generic;
    
    public partial class Apl_Rel_Usuarios_Roles
    {
        public int Rel_Usuario_Rol_ID { get; set; }
        public int Usuario_ID { get; set; }
        public int Rol_ID { get; set; }
        public int Empresa_ID { get; set; }
        public Nullable<int> Sucursal_ID { get; set; }
    
        public virtual Apl_Roles Apl_Roles { get; set; }
        public virtual Apl_Usuarios Apl_Usuarios { get; set; }
    }
}
