//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace datos_red_alert
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cat_Tramites_Pasos
    {
        public int Paso_Id { get; set; }
        public int Tramite_Id { get; set; }
        public string Descripcion { get; set; }
        public Nullable<int> Orden { get; set; }
        public byte[] Imagen { get; set; }
        public string Url_Imagen { get; set; }
        public string Usuario_Creo { get; set; }
        public Nullable<System.DateTime> Fecha_Creo { get; set; }
        public string Usuario_Modifico { get; set; }
        public Nullable<System.DateTime> Fecha_Modifico { get; set; }
    
        public virtual Cat_Tramites Cat_Tramites { get; set; }
    }
}
