//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace datos_red_alert
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cat_Ubicaciones
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cat_Ubicaciones()
        {
            this.Cat_Horarios_Ubicaciones = new HashSet<Cat_Horarios_Ubicaciones>();
            this.Cat_Medicos = new HashSet<Cat_Medicos>();
            this.Cat_Relacion_Medico_Hospital = new HashSet<Cat_Relacion_Medico_Hospital>();
        }
    
        public int Ubicacion_Id { get; set; }
        public int Tipo_Instalacion_Id { get; set; }
        public int Estatus_Id { get; set; }
        public string Nombre { get; set; }
        public Nullable<decimal> Longitud { get; set; }
        public Nullable<decimal> Latitud { get; set; }
        public Nullable<System.TimeSpan> Horario_Inicio { get; set; }
        public Nullable<System.TimeSpan> Horario_Termino { get; set; }
        public Nullable<bool> Lunes { get; set; }
        public Nullable<bool> Martes { get; set; }
        public Nullable<bool> Miercoles { get; set; }
        public Nullable<bool> Jueves { get; set; }
        public Nullable<bool> Viernes { get; set; }
        public Nullable<bool> Sabado { get; set; }
        public Nullable<bool> Domingo { get; set; }
        public string Usuario_Creo { get; set; }
        public Nullable<System.DateTime> Fecha_Creo { get; set; }
        public string Usuario_Modifico { get; set; }
        public Nullable<System.DateTime> Fecha_Modifico { get; set; }
        public Nullable<bool> Emergencias { get; set; }
        public string Telefono { get; set; }
        public string Telefono_Urgencias { get; set; }
        public string Sitio_Web_URL { get; set; }
        public string Observaciones { get; set; }
    
        public virtual Apl_Estatus Apl_Estatus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cat_Horarios_Ubicaciones> Cat_Horarios_Ubicaciones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cat_Medicos> Cat_Medicos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cat_Relacion_Medico_Hospital> Cat_Relacion_Medico_Hospital { get; set; }
        public virtual Cat_Tipo_Instalacion Cat_Tipo_Instalacion { get; set; }
    }
}
