//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace datos_red_alert
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cat_Relacion_Medico_Hospital
    {
        public int Relacion_Id { get; set; }
        public int Medico_Id { get; set; }
        public int Hospital_Id { get; set; }
        public Nullable<decimal> Costo_Consulta { get; set; }
    
        public virtual Cat_Medicos Cat_Medicos { get; set; }
        public virtual Cat_Ubicaciones Cat_Ubicaciones { get; set; }
    }
}
