//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace datos_red_alert
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cat_Medicos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cat_Medicos()
        {
            this.Apl_Opiniones = new HashSet<Apl_Opiniones>();
            this.Ope_Recordatorios = new HashSet<Ope_Recordatorios>();
            this.Cat_Relacion_Medico_Hospital = new HashSet<Cat_Relacion_Medico_Hospital>();
        }
    
        public int Medico_Id { get; set; }
        public int Especialidad_Id { get; set; }
        public int Estatus_Id { get; set; }
        public string Nombre { get; set; }
        public string Apellido_Paterno { get; set; }
        public string Apellido_Materno { get; set; }
        public string Email { get; set; }
        public string Telefono { get; set; }
        public string No_Cedula { get; set; }
        public string Usuario_Creo { get; set; }
        public Nullable<System.DateTime> Fecha_Creo { get; set; }
        public string Usuario_Modifico { get; set; }
        public Nullable<System.DateTime> Fecha_Modifico { get; set; }
        public string Imagen { get; set; }
        public Nullable<int> Hospital_Id { get; set; }
        public Nullable<bool> Emergencias { get; set; }
    
        public virtual Apl_Estatus Apl_Estatus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Apl_Opiniones> Apl_Opiniones { get; set; }
        public virtual Cat_Especialidades Cat_Especialidades { get; set; }
        public virtual Cat_Ubicaciones Cat_Ubicaciones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ope_Recordatorios> Ope_Recordatorios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cat_Relacion_Medico_Hospital> Cat_Relacion_Medico_Hospital { get; set; }
    }
}
