//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace datos_red_alert
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ERP_EJE_CENTRALEntities : DbContext
    {
        public ERP_EJE_CENTRALEntities()
            : base("name=ERP_EJE_CENTRALEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Apl_Accesos> Apl_Accesos { get; set; }
        public virtual DbSet<Apl_Bebes> Apl_Bebes { get; set; }
        public virtual DbSet<Apl_Estatus> Apl_Estatus { get; set; }
        public virtual DbSet<Apl_Historial_Bebes> Apl_Historial_Bebes { get; set; }
        public virtual DbSet<Apl_Menus> Apl_Menus { get; set; }
        public virtual DbSet<Apl_Modulos> Apl_Modulos { get; set; }
        public virtual DbSet<Apl_Opiniones> Apl_Opiniones { get; set; }
        public virtual DbSet<Apl_Parametros_Correo> Apl_Parametros_Correo { get; set; }
        public virtual DbSet<Apl_Registro_Accesos> Apl_Registro_Accesos { get; set; }
        public virtual DbSet<Apl_Rel_Usuarios_Roles> Apl_Rel_Usuarios_Roles { get; set; }
        public virtual DbSet<Apl_Roles> Apl_Roles { get; set; }
        public virtual DbSet<Apl_Roles_Sucursales> Apl_Roles_Sucursales { get; set; }
        public virtual DbSet<Apl_Tipos_Usuarios> Apl_Tipos_Usuarios { get; set; }
        public virtual DbSet<Apl_Usuarios_Movil> Apl_Usuarios_Movil { get; set; }
        public virtual DbSet<Apl_Usuarios_Password> Apl_Usuarios_Password { get; set; }
        public virtual DbSet<Cat_Consejos_Medicos> Cat_Consejos_Medicos { get; set; }
        public virtual DbSet<Cat_Empleados> Cat_Empleados { get; set; }
        public virtual DbSet<Cat_Especialidades> Cat_Especialidades { get; set; }
        public virtual DbSet<Cat_Horarios_Registro_Civil> Cat_Horarios_Registro_Civil { get; set; }
        public virtual DbSet<Cat_Horarios_Ubicaciones> Cat_Horarios_Ubicaciones { get; set; }
        public virtual DbSet<Cat_Medicos> Cat_Medicos { get; set; }
        public virtual DbSet<Cat_Mes_Aplicacion_Vacuna> Cat_Mes_Aplicacion_Vacuna { get; set; }
        public virtual DbSet<Cat_Registro_Civil> Cat_Registro_Civil { get; set; }
        public virtual DbSet<Cat_Relacion_Medico_Hospital> Cat_Relacion_Medico_Hospital { get; set; }
        public virtual DbSet<Cat_Tipo_Instalacion> Cat_Tipo_Instalacion { get; set; }
        public virtual DbSet<Cat_Tramites_Pasos> Cat_Tramites_Pasos { get; set; }
        public virtual DbSet<Cat_Ubicaciones> Cat_Ubicaciones { get; set; }
        public virtual DbSet<Cat_Vacunas> Cat_Vacunas { get; set; }
        public virtual DbSet<Ope_Aplicacion_Vacunas> Ope_Aplicacion_Vacunas { get; set; }
        public virtual DbSet<Ope_Cartilla_Vacunacion> Ope_Cartilla_Vacunacion { get; set; }
        public virtual DbSet<Ope_Recordatorios> Ope_Recordatorios { get; set; }
        public virtual DbSet<Ope_Recordatorios_Detalles> Ope_Recordatorios_Detalles { get; set; }
        public virtual DbSet<Tag> Tags { get; set; }
        public virtual DbSet<test> tests { get; set; }
        public virtual DbSet<Apl_Usuarios> Apl_Usuarios { get; set; }
        public virtual DbSet<Cat_Tramites> Cat_Tramites { get; set; }
    }
}
