//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace datos_red_alert
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ope_Recordatorios
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ope_Recordatorios()
        {
            this.Apl_Historial_Bebes = new HashSet<Apl_Historial_Bebes>();
            this.Ope_Recordatorios_Detalles = new HashSet<Ope_Recordatorios_Detalles>();
        }
    
        public int Id { get; set; }
        public string Nombre { get; set; }
        public Nullable<System.TimeSpan> Intervalo { get; set; }
        public Nullable<int> Dias { get; set; }
        public Nullable<System.DateTime> Inicio { get; set; }
        public Nullable<int> BebeId { get; set; }
        public string Tipo { get; set; }
        public Nullable<int> MedicoId { get; set; }
        public string Informacion { get; set; }
        public string ImagenUrl { get; set; }
        public string DoctorNoRegistrado { get; set; }
    
        public virtual Apl_Bebes Apl_Bebes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Apl_Historial_Bebes> Apl_Historial_Bebes { get; set; }
        public virtual Cat_Medicos Cat_Medicos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ope_Recordatorios_Detalles> Ope_Recordatorios_Detalles { get; set; }
    }
}
