//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace datos_red_alert
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ope_Aplicacion_Vacunas
    {
        public int Aplicacion_Vacuna_ID { get; set; }
        public Nullable<int> Relacion_Id { get; set; }
        public Nullable<int> BebeId { get; set; }
        public Nullable<System.DateTime> Fecha_Agenda_Vacuna { get; set; }
        public Nullable<System.DateTime> Fecha_Aplica_Vacuna { get; set; }
        public Nullable<System.DateTime> Fecha_Creo { get; set; }
        public Nullable<System.DateTime> Fecha_Modifica { get; set; }
    
        public virtual Apl_Bebes Apl_Bebes { get; set; }
        public virtual Ope_Cartilla_Vacunacion Ope_Cartilla_Vacunacion { get; set; }
    }
}
